// Generated by scripts/generate-catalog.ts. Do not edit by hand.
import type { Ladder } from "../schema";

import birds from "./birds.json";
import bridges from "./bridges.json";
import darkness from "./darkness.json";
import elevators from "./elevators.json";
import flying from "./flying.json";
import snakes from "./snakes.json";
import spiders from "./spiders.json";
import thunderstorms from "./thunderstorms.json";
import water from "./water.json";

export type CatalogEntry = { meta: { model: string | null; attempts: number; generatedAt: string }; ladder: Ladder };

export const CATALOG: Record<string, CatalogEntry> = {
  "birds": birds as CatalogEntry,
  "bridges": bridges as CatalogEntry,
  "darkness": darkness as CatalogEntry,
  "elevators": elevators as CatalogEntry,
  "flying": flying as CatalogEntry,
  "snakes": snakes as CatalogEntry,
  "spiders": spiders as CatalogEntry,
  "thunderstorms": thunderstorms as CatalogEntry,
  "water": water as CatalogEntry,
};
