/**
 * G6: pre-generate the v1 catalog fears (PRD §2.6) with the stronger model, lint them, and commit
 * the results so catalog chips never wait on live generation. Failing fears are reported, not written.
 *   pnpm catalog:generate [fearId ...]
 */
import { promises as fs } from "node:fs";
import path from "node:path";

import { CATALOG_MODELS, generateLadder } from "@/lib/ladder/generate";
import { CATALOG_FEARS } from "@/lib/ladder/catalog-fears";

const OUT = path.join(process.cwd(), "lib/ladder/catalog");

/** Static imports so the catalog ships inside the server bundle with no runtime file reads. */
async function writeIndex() {
  const ids = (await fs.readdir(OUT)).filter((f) => f.endsWith(".json")).map((f) => f.replace(/\.json$/, "")).sort();
  const name = (id: string) => id.replace(/[^a-z0-9]/gi, "_");
  const lines = [
    "// Generated by scripts/generate-catalog.ts. Do not edit by hand.",
    'import type { Ladder } from "../schema";',
    "",
    ...ids.map((id) => `import ${name(id)} from "./${id}.json";`),
    "",
    "export type CatalogEntry = { meta: { model: string | null; attempts: number; generatedAt: string }; ladder: Ladder };",
    "",
    "export const CATALOG: Record<string, CatalogEntry> = {",
    ...ids.map((id) => `  ${JSON.stringify(id)}: ${name(id)} as CatalogEntry,`),
    "};",
    "",
  ];
  await fs.writeFile(path.join(OUT, "index.ts"), lines.join("\n"));
}

async function main() {
  const only = new Set(process.argv.slice(2));
  const fears = CATALOG_FEARS.filter((f) => !only.size || only.has(f.id));
  const results: { id: string; ok: boolean; ms: number; attempts: number; model: string | null; error: string | null }[] = [];

  for (const fear of fears) {
    const started = Date.now();
    const result = await generateLadder(fear.prompt, fear.fearedOutcome, { models: CATALOG_MODELS, budgetMs: null, attempts: 6 });
    const ms = Date.now() - started;
    const ok = result.source === "generated";
    results.push({ id: fear.id, ok, ms, attempts: result.attempts, model: result.model, error: result.error });
    console.log(`${fear.id}: ${ok ? "ok" : "FAILED"} in ${ms} ms (${result.attempts} attempts, ${result.model})${ok ? "" : ` ${result.error}`}`);
    if (!ok) {
      for (const issue of result.lint.slice(0, 12)) console.log(`  ${issue.path}: ${issue.rule}: ${issue.text}`);
      continue;
    }
    const ladder = { ...result.ladder, fearId: fear.id };
    await fs.writeFile(
      path.join(OUT, `${fear.id}.json`),
      `${JSON.stringify({ meta: { model: result.model, attempts: result.attempts, generatedAt: new Date().toISOString(), lint: [] }, ladder }, null, 2)}\n`,
    );
  }

  await writeIndex();
  await fs.mkdir("evidence/breadth", { recursive: true });
  await fs.writeFile("evidence/breadth/catalog-generation.json", `${JSON.stringify({ generatedAt: new Date().toISOString(), results }, null, 2)}\n`);
  if (results.some((r) => !r.ok)) process.exitCode = 1;
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
